nodeLinker: node-modules
packageExtensions:
  debug@*:
    peerDependenciesMeta:
      supports-color:
        optional: true

pnpMode: loose
checksumBehavior: update
yarnPath: .yarn/releases/yarn-3.2.2.cjs
