name: Guardian Tests
on:
  push:
    branches: [main, development]
  pull_request:
    branches: [main, development]
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 20
      - name: Enable corepack
        run: corepack enable
      - name: Activate yarn
        run: corepack prepare yarn@3.2.2 --activate
      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly
      - name: Install playwright browsers
        run: npx playwright install --with-deps
      - name: Install dependencies
        run: yarn install
      - name: Run Guardian tests
        run: yarn test:gui
      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
